require 'thor'
require 'yaml'
require 'fileutils'
require 'erubis'
require 'git'
require 'bootstrap'
require 'font-awesome-sass'

require 'skellington/version'
require 'skellington/generator'
require 'skellington/cli'
require 'skellington/helpers'
require 'skellington/template'
